#!/usr/bin/env python3
from _yadata_types import Tag
import sys

with open('tags.txt') as f:
    for line in f:
        line=line.strip()
        if not line:
            continue
        g=Tag({'tag':line})
        print('---')
        sys.stdout.write(g.to_yaml())



